//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opt.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OPT")]
        public string ApplicationName {
            get {
                return ((string)(this["ApplicationName"]));
            }
            set {
                this["ApplicationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ValuesDecimalPlaces {
            get {
                return ((int)(this["ValuesDecimalPlaces"]));
            }
            set {
                this["ValuesDecimalPlaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Abs,Acos,Asin,Atan,Ceiling,Cos,Exp,Floor,IEEERemainder,Log,Log10,Max,Min,Pow,Roun" +
            "d,Sign,Sin,Sqrt,Tan,Truncate")]
        public string RestrictedVariableIdentifiers {
            get {
                return ((string)(this["RestrictedVariableIdentifiers"]));
            }
            set {
                this["RestrictedVariableIdentifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Models\\numpk.txt")]
        public string QuantitiesFileName {
            get {
                return ((string)(this["QuantitiesFileName"]));
            }
            set {
                this["QuantitiesFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Models\\par.opt")]
        public string ParametersFileName {
            get {
                return ((string)(this["ParametersFileName"]));
            }
            set {
                this["ParametersFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Models\\fun.opt")]
        public string ResultsFileName {
            get {
                return ((string)(this["ResultsFileName"]));
            }
            set {
                this["ResultsFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("license.xml")]
        public string LicenseFileName {
            get {
                return ((string)(this["LicenseFileName"]));
            }
            set {
                this["LicenseFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOldXmlProvider {
            get {
                return ((bool)(this["UseOldXmlProvider"]));
            }
            set {
                this["UseOldXmlProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseInvariantCulture {
            get {
                return ((bool)(this["UseInvariantCulture"]));
            }
            set {
                this["UseInvariantCulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModelFilePath {
            get {
                return ((string)(this["ModelFilePath"]));
            }
            set {
                this["ModelFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CalcAppFilePath {
            get {
                return ((string)(this["CalcAppFilePath"]));
            }
            set {
                this["CalcAppFilePath"] = value;
            }
        }
    }
}
