//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opt.Bionic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public uint MaxGenerations {
            get {
                return ((uint)(this["MaxGenerations"]));
            }
            set {
                this["MaxGenerations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public uint DescendantsNum {
            get {
                return ((uint)(this["DescendantsNum"]));
            }
            set {
                this["DescendantsNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public uint NeighborhoodSizePercent {
            get {
                return ((uint)(this["NeighborhoodSizePercent"]));
            }
            set {
                this["NeighborhoodSizePercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseRecordPoint {
            get {
                return ((bool)(this["UseRecordPoint"]));
            }
            set {
                this["UseRecordPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ApplyElitism {
            get {
                return ((bool)(this["ApplyElitism"]));
            }
            set {
                this["ApplyElitism"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public uint InitialPopulationSize {
            get {
                return ((uint)(this["InitialPopulationSize"]));
            }
            set {
                this["InitialPopulationSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public uint DescendantsRangePercent {
            get {
                return ((uint)(this["DescendantsRangePercent"]));
            }
            set {
                this["DescendantsRangePercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ValuesDecimalPlaces {
            get {
                return ((int)(this["ValuesDecimalPlaces"]));
            }
            set {
                this["ValuesDecimalPlaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public uint SelectionCap {
            get {
                return ((uint)(this["SelectionCap"]));
            }
            set {
                this["SelectionCap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-m {0} -w \"1. Полесье + КПР-9.xmcd\" -q")]
        public string CalcAppCommandLineArgsFormat {
            get {
                return ((string)(this["CalcAppCommandLineArgsFormat"]));
            }
            set {
                this["CalcAppCommandLineArgsFormat"] = value;
            }
        }
    }
}
